# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GitFood Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev pkg-config python3-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 svglib m2r rst2pdf Pillow pyenchant
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check for spelling errors in _posts (update src/dict.txt if needed)
      run: |
        python ./src/spellchecker.py ./docs/_posts/*.md    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Generate combined cook book restructuredtext
      run: |
        python ./src/gitfood.py toc.csv  1.1.1 > GitFood.rst
    - name: Check for spelling errors in combined GitFood.rst (update src/dict.txt if needed)
      run: |
        echo "No RST spell checking yet."
    - name: Generage cook book PDF 
      run: |
        rst2pdf GitFood.rst
