# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish GitFood Cook Book

on:
  workflow_dispatch:
    inputs:
      release_semver:
        description: 'The Semantic Version number of the release'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 svglib m2r rst2pdf Pillow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check for spelling errors in _posts (update src/dict.txt if needed)
      run: |
        python ./src/spellchecker.py ./docs/_posts/*.md
    - name: Generate combined cook book markdown
      run: |
        python ./src/gitfood.py toc.csv > GitFood.rst
    - name: Check for spelling errors in combined GitFood.md (update src/dict.txt if needed)
      run: |
        echo "No RST spell checking yet."
    - name: Generage cook book PDF (this takes a little time)
      run: |
        rst2pdf GitFood.rst -s vs
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_semver }}
        release_name: Release ${{ github.event.inputs.release_semver }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./GitFood.pdf
        asset_name: GitFood.pdf
        asset_content_type: application/pdf
